version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ridenow
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    command: uvicorn gateway.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./gateway:/app/gateway
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  worker:
    build: .
    command: python /app/worker/ride_worker.py
    volumes:
      - ./worker:/app/worker
      - ./gateway:/app/gateway   # mount gateway for imports
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

volumes:
  db_data:
