version: "3.9"  # version can be omitted, but kept for clarity

services:

  db:
    image: mysql:8
    container_name: mysql_container
    platform: linux/arm64   # ensure compatibility with M4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ridenow
      MYSQL_USER: ridenow_user
      MYSQL_PASSWORD: ridenow_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    container_name: redis_container
    platform: linux/arm64
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridefastapi
    command: uvicorn gateway.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql+pymysql://ridenow_user:ridenow_pass@db:3306/ridenow
      REDIS_URL: redis://redis:6379
    restart: always

volumes:
  - ./gateway:/app/gateway
